### ISSUE TITLE
allow users to change the File::HomeDir in use

### ISSUE THREAD

**Issue by soonix** [stevieb9/berrybrew#121]
discussion in https://www.perlmonks.org/?node_id=1225037
my solution was to remove ...\perl\vendor\lib\Portable\HomeDir.pm
(see https://www.perlmonks.org/?node_id=1225091)

Since berrybrew has a different scope than a "normal" portable perl, it would make sense to do this upon `install` or even `fetch`.

**Comment by pryrt** [comment]
I don't think `fetch` would be the right place, since that's only updating the list of perls that could be installed.  

My initial thoughts, after reading the thread, are that it should be an option in the config file -- just in case an existing user has grown accustomed to the behavior, we wouldn't want to break it.  I'd probably say if the variable were _missing_ from the config file, or set false, then don't change the use of Portable::HomeDir; but if it's true, then remove the module during `install`.  

I'm also curious whether it should just affect Portable::HomeDir, or whether some of the other [Portable::](https://metacpan.org/pod/Portable) might also cause unexpected results.  My _guess_ is that the ::CPAN and ::Config and ::LoadYaml will probably want to stay Portable::, but the ::FileSpec (as well as ::HomeDir, of course) might want to be de-stickified.  Hmm, not sure.  They're all somewhat intertwined with each other.  That will take some more thought, and maybe some experimentation...

**Comment by stevieb9** [comment]
@pryrt I've updated the PM thread with a couple of ideas. I'm still trying to figure out the ramifications as it appears you are.

First thoughts:

- config file directive, defaults to existing functionality
- possible `berrybrew install x.xx --win_home` command flag addition, making it configurable on each instance installation

Note that tests broke yesterday after releasing v1.19. Essentially, I added an updated `perls.json` file, and apparently, some of our tests are looking for exact version numbers. I'll clear that up this morning. 

See #118 for details.
