### ISSUE TITLE
Removing versions of Perl can cause breakage to other tools

### ISSUE THREAD

**Issue by autarch** [stevieb9/berrybrew#217]
I've been working on a set of CI helpers for Perl projects. For Windows testing, I install Berrybrew and then use that to install a Perl. I had it installing `5.30.0_64` but that version has gone away in the latest berrybrew release, which broke my tools.

It'd be really nice if existing builds were never removed for backwards compatibility.

**Comment by stevieb9** [comment]
Thanks for reporting. It should be registering it as custom automatically, but I will implement it so the existing Perl remains in place despite the fact that older versions are removed from the Strawberry releases file, which is where the available Perls are listed from.

I have a release scheduled for right around Christmas, so I will include a fix for this in that release.

**Comment by stevieb9** [comment]
In `PerlUpdateAvailableList()`, remove the logic that limits the number of Perls written to the `perls.json` file, and instead, add similar checks in `Available()`:

    if (perls.Contains(bbMajorVersion) && ! allPerls)
        continue;

When listing what versions are available with `berrybrew available`, perform the logic that limits to the most recently released major version, **after** we do the `PerlIsInstalled()` check. 

This way, multiple major version numbers will remain unaffected, if someone has a previous major release previously installed (eg: `5.30.1_64` has been released, but user already has a `5.30.0_64` instance installed). It will also correct the issue on full blown `berrybrew` upgrades, not just when using `berybrew fetch`.

**Comment by stevieb9** [comment]
This has been addressed and the fix will be included in the next release (1.30, sometime around Christmas 2019).

By default, `available` still only lists the most recent point release of a major version (unless the new `all` option is sent in with it), but in the background, all Perls are located in the `perls.json` file. This allows the software to allow a previous point release to be acknowledged as valid, instead of being recognized as an oprhan, and having to be re-registered as a custom install.

`fetch` now retrieves all available Perls, and the separation of old and new point releases has been moved to the various methods that display/return the Perl instances.

**Comment by autarch** [comment]
Thanks! I also tweaked my project to not hard-code specific Perl versions for when using Berrybrew but I think it's generally good to preserve old version availability.

**Comment by stevieb9** [comment]
I agree with you, and the new way is much better in numerous respects. Now, all Perls that are listed are available to the user, with a switch to enable displaying them all, or just the most recent point release of a major version (except of course if a Perl already installed isn't the newest, it'll be shown anyhow).

I've made several significant improvements and fixes (and I'm still working on it now), and still plan to release in the coming couple of days.
